import { ALT, BACKSPACE, CONTROL, DELETE, DOWN_ARROW, EIGHT, END, ENTER, FIVE, FOUR, HOME, INSERT, LEFT_ARROW, NINE, NUMPAD_EIGHT, NUMPAD_FIVE, NUMPAD_FOUR, NUMPAD_NINE, NUMPAD_ONE, NUMPAD_SEVEN, NUMPAD_SIX, NUMPAD_THREE, NUMPAD_TWO, NUMPAD_ZERO, ONE, RIGHT_ARROW, SEVEN, SHIFT, SIX, TAB, THREE, TWO, UP_ARROW, ZERO } from '@angular/cdk/keycodes';

export const PERIOD_DECIMAL = 190;
export const NUMPAD_DECIMAL = 110;

export const FUNCTIONAL = [
  BACKSPACE,
  TAB,
  ENTER,
  SHIFT,
  CONTROL,
  ALT,
  END,
  HOME,
  LEFT_ARROW,
  UP_ARROW,
  RIGHT_ARROW,
  DOWN_ARROW,
  INSERT,
  DELETE
];

export const NUMERIC = [
  ONE,
  TWO,
  THREE,
  FOUR,
  FIVE,
  SIX,
  SEVEN,
  EIGHT,
  NINE,
  ZERO,
  NUMPAD_ONE,
  NUMPAD_TWO,
  NUMPAD_THREE,
  NUMPAD_FOUR,
  NUMPAD_FIVE,
  NUMPAD_SIX,
  NUMPAD_SEVEN,
  NUMPAD_EIGHT,
  NUMPAD_NINE,
  NUMPAD_ZERO,
  NUMPAD_DECIMAL,
  PERIOD_DECIMAL
];
